/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.MaintenanceEnterpriseAdmin;

import java.awt.CardLayout;
import java.awt.Color;

import javax.swing.JPanel;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;

/**
 *
 * @author shaur
 */
public class MaintenanceMasterAdminWorkAreaJPanel extends javax.swing.JPanel {
    Enterprise enterprise;
    JPanel userProcessContainer;
    Network network;
    Organization organization;
    EcoSystem system;
    UserAccount account;

    /**
     * Creates new form SparePartsAdminJPanel
     */
    public MaintenanceMasterAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
        this.organization = organization;
        this.system = business;
        this.account = account;
        manageOrganization();
    }
    
    public void manageOrganization(){
        ManageOrgPanel.setBackground(new Color(236,113,107));
        
        ManageOrgAdminPanel.setBackground(new Color(215,81,81));
        ManageMaintanenceOrg manageOrgPanel = new ManageMaintanenceOrg(MaintanenceRightPanel, enterprise);
        MaintanenceRightPanel.add("ManageOrganization",manageOrgPanel);
        CardLayout layout = (CardLayout) MaintanenceRightPanel.getLayout();
        layout.next(MaintanenceRightPanel);
    }
    
    public void manageOrgAdmin(){
        ManageOrgAdminPanel.setBackground(new Color(236,113,107));
        ManageOrgPanel.setBackground(new Color(215,81,81));
        
        ManageEnterpriseOrgAdmin manageOrgAdminPanel = new ManageEnterpriseOrgAdmin(MaintanenceRightPanel, enterprise, system);
        MaintanenceRightPanel.add("MangeOrganizationAdmin",manageOrgAdminPanel);
        CardLayout layout = (CardLayout) MaintanenceRightPanel.getLayout();
        layout.next(MaintanenceRightPanel);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MaintanenceAdminWorkArea = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ManageOrgPanel = new javax.swing.JPanel();
        LabeManageOrganization = new javax.swing.JLabel();
        ManageOrgAdminPanel = new javax.swing.JPanel();
        LabelManageOrgAdmin = new javax.swing.JLabel();
        MaintanenceRightPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        MaintanenceAdminWorkArea.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(191, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageOrgPanel.setBackground(new java.awt.Color(191, 0, 0));
        ManageOrgPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageOrgPanelMousePressed(evt);
            }
        });

        LabeManageOrganization.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LabeManageOrganization.setForeground(new java.awt.Color(0, 51, 153));
        LabeManageOrganization.setText("Manage Organization");
        LabeManageOrganization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabeManageOrganizationMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ManageOrgPanelLayout = new javax.swing.GroupLayout(ManageOrgPanel);
        ManageOrgPanel.setLayout(ManageOrgPanelLayout);
        ManageOrgPanelLayout.setHorizontalGroup(
            ManageOrgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageOrgPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(LabeManageOrganization, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        ManageOrgPanelLayout.setVerticalGroup(
            ManageOrgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageOrgPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LabeManageOrganization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(ManageOrgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 50));

        ManageOrgAdminPanel.setBackground(new java.awt.Color(191, 0, 0));
        ManageOrgAdminPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageOrgAdminPanelMousePressed(evt);
            }
        });

        LabelManageOrgAdmin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LabelManageOrgAdmin.setForeground(new java.awt.Color(0, 51, 153));
        LabelManageOrgAdmin.setText("Manage My Admins");
        LabelManageOrgAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelManageOrgAdminMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ManageOrgAdminPanelLayout = new javax.swing.GroupLayout(ManageOrgAdminPanel);
        ManageOrgAdminPanel.setLayout(ManageOrgAdminPanelLayout);
        ManageOrgAdminPanelLayout.setHorizontalGroup(
            ManageOrgAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageOrgAdminPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(LabelManageOrgAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        ManageOrgAdminPanelLayout.setVerticalGroup(
            ManageOrgAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageOrgAdminPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LabelManageOrgAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(ManageOrgAdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 50));

        MaintanenceRightPanel.setBackground(new java.awt.Color(255, 255, 255));
        MaintanenceRightPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout MaintanenceAdminWorkAreaLayout = new javax.swing.GroupLayout(MaintanenceAdminWorkArea);
        MaintanenceAdminWorkArea.setLayout(MaintanenceAdminWorkAreaLayout);
        MaintanenceAdminWorkAreaLayout.setHorizontalGroup(
            MaintanenceAdminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaintanenceAdminWorkAreaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MaintanenceRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MaintanenceAdminWorkAreaLayout.setVerticalGroup(
            MaintanenceAdminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addComponent(MaintanenceRightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(MaintanenceAdminWorkArea, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ManageOrgPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageOrgPanelMousePressed
        // TODO add your handling code here:
        manageOrganization();
    }//GEN-LAST:event_ManageOrgPanelMousePressed

    private void LabeManageOrganizationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabeManageOrganizationMousePressed
        // TODO add your handling code here:
        manageOrganization();
    }//GEN-LAST:event_LabeManageOrganizationMousePressed

    private void ManageOrgAdminPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageOrgAdminPanelMousePressed
        // TODO add your handling code here:
        manageOrgAdmin();
    }//GEN-LAST:event_ManageOrgAdminPanelMousePressed

    private void LabelManageOrgAdminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelManageOrgAdminMousePressed
        // TODO add your handling code here:
        manageOrgAdmin();
    }//GEN-LAST:event_LabelManageOrgAdminMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabeManageOrganization;
    private javax.swing.JLabel LabelManageOrgAdmin;
    private javax.swing.JPanel MaintanenceAdminWorkArea;
    private javax.swing.JPanel MaintanenceRightPanel;
    private javax.swing.JPanel ManageOrgAdminPanel;
    private javax.swing.JPanel ManageOrgPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
