/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.MaintenanceEnterpriseAdmin;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.BodyShop;
import Business.Organization.Mechanics;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Utils.HeaderColors;

/**
 *
 * @author shaur
 */
public class ManageEnterpriseOrgAdmin extends javax.swing.JPanel {
    private JPanel container;
    private Enterprise enterprise;
    private EcoSystem ecosystem;
//    OrganizationDirectory organizationDirectory;
//    Employee employee;
//    Organization organization;

    /**
     * Creates new form ManageEmployee
     */
    public ManageEnterpriseOrgAdmin(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.enterprise = enterprise;
        this.container = userProcessContainer;
        this.ecosystem = system;
//        this.organizationDirectory = organizationDirectory;
//        this.organization = organization;
         tblManageOrgAdmin.getTableHeader().setDefaultRenderer(new HeaderColors());
        populateOrganizationComboBox();
       // employeeJComboBox.removeAllItems();
        populateTable();
       
    }
    
                                            
    public void resetFields() {
        TFMaintanenceEmployeeUname.setText("");
    }
    private void populateOrganizationComboBox() {
        organizationJComboBox.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            organizationJComboBox.addItem(organization);
        }
    }
    
    private void populateTable(){
        tblManageOrgAdmin.getTableHeader().setDefaultRenderer(new HeaderColors());
        DefaultTableModel model = (DefaultTableModel) tblManageOrgAdmin.getModel();

        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if(organization instanceof BodyShop
               ||organization instanceof Mechanics){
                for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                    Object row[] = new Object[2];
                    row[0] = ua;
                    row[1] = ua.getRole();
                    ((DefaultTableModel) tblManageOrgAdmin.getModel()).addRow(row);
                }
            }
        }
        
        
        
    }
    
    private void populateRoleComboBox(Organization organization) {
        BoxRole.removeAllItems();
        for (Role role : organization.getSupportedRole()){
            BoxRole.addItem(role);
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageOrgAdmin = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        TFMaintanenceEmployeePass = new javax.swing.JTextField();
        ButtonAddOrgAdmin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TFMaintanenceEmployeeUname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BoxRole = new javax.swing.JComboBox();
        organizationJComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Manage Employee");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 230, 40));

        tblManageOrgAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Organization"
            }
        ));
        jScrollPane1.setViewportView(tblManageOrgAdmin);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 410, 90));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, 20));
        add(TFMaintanenceEmployeePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 140, -1));

        ButtonAddOrgAdmin.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAddOrgAdmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonAddOrgAdmin.setForeground(new java.awt.Color(0, 51, 153));
        ButtonAddOrgAdmin.setText("Add Employee");
        ButtonAddOrgAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddOrgAdminActionPerformed(evt);
            }
        });
        add(ButtonAddOrgAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 120, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Role");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("Username");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, 20));
        add(TFMaintanenceEmployeeUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 140, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("Organization");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, 20));

        BoxRole.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BoxRole.setForeground(new java.awt.Color(25, 56, 82));
        BoxRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxRoleActionPerformed(evt);
            }
        });
        add(BoxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 140, -1));

        organizationJComboBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        organizationJComboBox.setForeground(new java.awt.Color(25, 56, 82));
        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });
        add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAddOrgAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddOrgAdminActionPerformed
        // TODO add your handling code here:
        String userName = TFMaintanenceEmployeeUname.getText();
        String password = TFMaintanenceEmployeePass.getText();
        if("".equals(userName)) {
            JOptionPane.showMessageDialog(null, "Please enter username");
        }else if(!ecosystem.checkIfUserIsUnique(userName)) {
            JOptionPane.showMessageDialog(null, "Please enter unique username");
        }else if("".equals(password)) {
            JOptionPane.showMessageDialog(null, "Please enter password");
        }else {
            Organization organization = (Organization) organizationJComboBox.getSelectedItem();
            //Employee employee = (Employee) employeeComboBox2.getSelectedItem();
            Role role = (Role) BoxRole.getSelectedItem();
            Employee employee = organization.getEmployeeDirectory().createEmployee(userName);
            organization.getUserAccountDirectory().createUserAccount(userName, password,employee, role);
            populateTable();
            JOptionPane.showMessageDialog(null, "User is created successfully");
            TFMaintanenceEmployeeUname.setText("");
            TFMaintanenceEmployeePass.setText("");
        }
    }//GEN-LAST:event_ButtonAddOrgAdminActionPerformed

    private void BoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxRoleActionPerformed
        
    }//GEN-LAST:event_BoxRoleActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        Organization organization = (Organization) organizationJComboBox.getSelectedItem();
        if (organization != null){
            //            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
        }
    }//GEN-LAST:event_organizationJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BoxRole;
    private javax.swing.JButton ButtonAddOrgAdmin;
    private javax.swing.JTextField TFMaintanenceEmployeePass;
    private javax.swing.JTextField TFMaintanenceEmployeeUname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTable tblManageOrgAdmin;
    // End of variables declaration//GEN-END:variables
}
