/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.BodyShopOrganization;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import Business.EcoSystem;
import Business.Customer.Customer;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Workqueue.ServiceRequest;
import Business.Workqueue.ServiceRequestDirectory;
import Utils.HeaderColors;
import java.util.ArrayList;

/**
 *
 * @author shaur
 */
public class ManageBodyShopRequest extends javax.swing.JPanel {

	JPanel userProcessContainer;
	UserAccount account;
	Organization organization;
	Enterprise enterprise;
	Network network;
	EcoSystem business;
	ServiceRequestDirectory servicerequestdirectory;
	Customer customer;

	/**
	 * Creates new form ManageRequest
	 */
	public ManageBodyShopRequest(JPanel userProcessContainer, Network network, Enterprise enterprise,
			UserAccount account, EcoSystem business, Organization organization, ServiceRequestDirectory sd) {
		initComponents();
		this.userProcessContainer = userProcessContainer;
		this.enterprise = enterprise;
		this.business = business;
		this.organization = organization;
		this.account = account;
		this.servicerequestdirectory = sd;
		this.network = network;
		tblBodyShop.getTableHeader().setDefaultRenderer(new HeaderColors());
		populateTable();

		populateEmployeeCombo();
	}

	private void populateEmployeeCombo() {
		BoxAssignBodyShopEmployee.removeAllItems();
//        if(BoxAssignMaintanenceOrg )

	}

	private void populateTable() {
		tblBodyShop.getTableHeader().setDefaultRenderer(new HeaderColors());
		DefaultTableModel model = (DefaultTableModel) tblBodyShop.getModel();
		model.setRowCount(0);
		ArrayList<UserAccount> userAccountList = business.getUserAccountDirectory().getUserAccountList();
		for (UserAccount account : userAccountList) {
			for (ServiceRequest wr : account.getServiceDirectory().getServiceRequestList()) {
				if (wr.getStatus().equalsIgnoreCase("New") || wr.getStatus().equalsIgnoreCase("Assigned to me")
						|| wr.getStatus().equalsIgnoreCase("Processed by BodyShop"))
					if (wr.getEnterprisetype().getValue().equalsIgnoreCase("Maintanence")
							|| wr.getEnterprisetype().getValue().equalsIgnoreCase("All")) {
						Object[] row = new Object[model.getColumnCount()];
						row[0] = ((ServiceRequest) wr);
						row[1] = ((ServiceRequest) wr).getName();
						row[2] = ((ServiceRequest) wr).getModel();
						row[3] = ((ServiceRequest) wr).getMake();
						row[4] = ((ServiceRequest) wr).getModelyear();
						row[5] = ((ServiceRequest) wr).getRegno();
						row[6] = ((ServiceRequest) wr).getEnterprisetype().getValue();
						row[7] = ((ServiceRequest) wr).getStatus();
						row[8] = ((ServiceRequest) wr).getSender();

						model.addRow(row);
					}

			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblBodyShop = new javax.swing.JTable();
		jLabel4 = new javax.swing.JLabel();
		BoxAssignBodyShopEmployee = new javax.swing.JComboBox<>();
		jButton2 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();

		setBackground(new java.awt.Color(255, 255, 255));
		setPreferredSize(new java.awt.Dimension(1060, 300));
		setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 51, 153));
		jLabel1.setText("Manage Service Request");
		add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 300, 40));

		tblBodyShop.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null } },
				new String[] { "Request ID", "Name", "Model", "Make", "Model Year", "Registration number",
						"Service Requested", "Status", "Sender" }));
		jScrollPane1.setViewportView(tblBodyShop);

		add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 740, 90));

		jLabel4.setBackground(new java.awt.Color(255, 255, 255));
		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(204, 0, 51));
		jLabel4.setText("Employee");
		add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, 20));

		BoxAssignBodyShopEmployee.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		add(BoxAssignBodyShopEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 110, -1));

		jButton2.setBackground(new java.awt.Color(255, 255, 255));
		jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jButton2.setForeground(new java.awt.Color(0, 51, 153));
		jButton2.setText("Assign");
		jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jButton2MousePressed(evt);
			}
		});
		add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 120, 20));

		jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jButton1.setForeground(new java.awt.Color(0, 51, 153));
		jButton1.setText("Process");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jButton1MousePressed(evt);
			}
		});
		add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 120, -1));
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton2MousePressed
		// TODO add your handling code here:
		int count = tblBodyShop.getSelectedRowCount();
		if (count != 1) {
			JOptionPane.showMessageDialog(null, "Select one row", "Warning", JOptionPane.WARNING_MESSAGE);
		} else {
			int selectedRow = tblBodyShop.getSelectedRow();
			ServiceRequest sr = (ServiceRequest) tblBodyShop.getValueAt(selectedRow, 0);
			if (sr.getStatus().equals("New")) {

				String msg = JOptionPane.showInputDialog("Additional Message");
				sr.setStatus("Assigned to me");
			}
			populateTable();
		}
	}// GEN-LAST:event_jButton2MousePressed

	private void jButton1MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton1MousePressed
		// TODO add your handling code here:
		int count = tblBodyShop.getSelectedRowCount();
		if (count != 1) {
			JOptionPane.showMessageDialog(null, "Select one row", "Warning", JOptionPane.WARNING_MESSAGE);
		} else {
			int selectedRow = tblBodyShop.getSelectedRow();
			ServiceRequest sr = (ServiceRequest) tblBodyShop.getValueAt(selectedRow, 0);
			if (sr.getStatus().equals("New")) {
				JOptionPane.showMessageDialog(null, "First assign process");
			} else if (sr.getStatus().equals("Assigned to me")) {
				sr.setStatus("Processed by BodyShop");
				sr.setSender(account);
			}
			populateTable();
		}
	}// GEN-LAST:event_jButton1MousePressed

	private void jButton3MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton3MousePressed
		// TODO add your handling code here:
		int count = tblBodyShop.getSelectedRowCount();
		if (count != 1) {
			JOptionPane.showMessageDialog(null, "Select one row", "Warning", JOptionPane.WARNING_MESSAGE);
		} else {
			int selectedRow = tblBodyShop.getSelectedRow();
			ServiceRequest sr = (ServiceRequest) tblBodyShop.getValueAt(selectedRow, 0);
			if (sr.getStatus().equals("New")) {
				JOptionPane.showMessageDialog(null, "First assign process");
			} else if (sr.getStatus().equals("Assigned")) {
				sr.setStatus("Processed by BodyShop");
				sr.setSender(account);
			}
		}

	}// GEN-LAST:event_jButton3MousePressed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton3ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox<String> BoxAssignBodyShopEmployee;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tblBodyShop;
	// End of variables declaration//GEN-END:variables
}
