/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AccountsMasterAdmin;

import java.awt.CardLayout;
import java.awt.Color;

import javax.swing.JPanel;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;

/**
 *
 * @author shaur
 */
public class AccountsMasterAdminPanel extends javax.swing.JPanel {
     Enterprise enterprise;
     JPanel userProcessContainer;
    Network network;
    Organization organization;
    EcoSystem system;
    UserAccount account;

    /**
     * Creates new form CleaningAdminmasterAdminPanel
     */
    public AccountsMasterAdminPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
        this.organization = organization;
        this.system = business;
        this.account = account;
        manageOrganization();
    }
    public void manageOrganization(){
        ManageOrgPanel.setBackground(new Color(236,113,107));
        
        ManageOrgAdminPanel.setBackground(new Color(215,81,81));
        ManageAccountOrg manageOrgPanel = new ManageAccountOrg(AccountsAdminRightPanel,enterprise);
        AccountsAdminRightPanel.add("ManageEmployee",manageOrgPanel);
        CardLayout layout = (CardLayout) AccountsAdminRightPanel.getLayout();
        layout.next(AccountsAdminRightPanel);
    }
    
    public void manageOrgAdmin(){
        ManageOrgAdminPanel.setBackground(new Color(236,113,107));
        ManageOrgPanel.setBackground(new Color(215,81,81));
        
        ManageAccountsOrgAdmin manageOrgAdminPanel = new ManageAccountsOrgAdmin(AccountsAdminRightPanel,enterprise, system);
        AccountsAdminRightPanel.add("MangeRequest",manageOrgAdminPanel);
        CardLayout layout = (CardLayout) AccountsAdminRightPanel.getLayout();
        layout.next(AccountsAdminRightPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ManageOrgPanel = new javax.swing.JPanel();
        labelAccountsManageOrg = new javax.swing.JLabel();
        ManageOrgAdminPanel = new javax.swing.JPanel();
        labelAccountsAdminManageEmployee = new javax.swing.JLabel();
        AccountsAdminRightPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1060, 720));

        jPanel2.setBackground(new java.awt.Color(191, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageOrgPanel.setBackground(new java.awt.Color(191, 0, 0));
        ManageOrgPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageOrgPanelMousePressed(evt);
            }
        });

        labelAccountsManageOrg.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelAccountsManageOrg.setForeground(new java.awt.Color(0, 51, 153));
        labelAccountsManageOrg.setText("Manage Organization");
        labelAccountsManageOrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelAccountsManageOrgMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ManageOrgPanelLayout = new javax.swing.GroupLayout(ManageOrgPanel);
        ManageOrgPanel.setLayout(ManageOrgPanelLayout);
        ManageOrgPanelLayout.setHorizontalGroup(
            ManageOrgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageOrgPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelAccountsManageOrg, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        ManageOrgPanelLayout.setVerticalGroup(
            ManageOrgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageOrgPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelAccountsManageOrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(ManageOrgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 50));

        ManageOrgAdminPanel.setBackground(new java.awt.Color(191, 0, 0));
        ManageOrgAdminPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageOrgAdminPanelMousePressed(evt);
            }
        });

        labelAccountsAdminManageEmployee.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelAccountsAdminManageEmployee.setForeground(new java.awt.Color(0, 51, 153));
        labelAccountsAdminManageEmployee.setText("Manage My Admins");
        labelAccountsAdminManageEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelAccountsAdminManageEmployeeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ManageOrgAdminPanelLayout = new javax.swing.GroupLayout(ManageOrgAdminPanel);
        ManageOrgAdminPanel.setLayout(ManageOrgAdminPanelLayout);
        ManageOrgAdminPanelLayout.setHorizontalGroup(
            ManageOrgAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageOrgAdminPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelAccountsAdminManageEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        ManageOrgAdminPanelLayout.setVerticalGroup(
            ManageOrgAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageOrgAdminPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelAccountsAdminManageEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(ManageOrgAdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 50));

        AccountsAdminRightPanel.setBackground(new java.awt.Color(255, 255, 255));
        AccountsAdminRightPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AccountsAdminRightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AccountsAdminRightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void labelAccountsManageOrgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAccountsManageOrgMousePressed
        // TODO add your handling code here:
        manageOrganization();
    }//GEN-LAST:event_labelAccountsManageOrgMousePressed

    private void ManageOrgPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageOrgPanelMousePressed
        // TODO add your handling code here:
        manageOrganization();
    }//GEN-LAST:event_ManageOrgPanelMousePressed

    private void labelAccountsAdminManageEmployeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAccountsAdminManageEmployeeMousePressed
        // TODO add your handling code here:
        manageOrgAdmin();
    }//GEN-LAST:event_labelAccountsAdminManageEmployeeMousePressed

    private void ManageOrgAdminPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageOrgAdminPanelMousePressed
        // TODO add your handling code here:
        manageOrgAdmin();
    }//GEN-LAST:event_ManageOrgAdminPanelMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountsAdminRightPanel;
    private javax.swing.JPanel ManageOrgAdminPanel;
    private javax.swing.JPanel ManageOrgPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAccountsAdminManageEmployee;
    private javax.swing.JLabel labelAccountsManageOrg;
    // End of variables declaration//GEN-END:variables
}
