/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.MechanicOrganization;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Workqueue.ServiceRequest;
import Utils.HeaderColors;

/**
 *
 * @author shaur
 */
public class ManageOrgRequest extends javax.swing.JPanel {

	JPanel userProcessContainer;
	UserAccount account;
	Organization organization;
	Enterprise enterprise;
	Network network;
	EcoSystem business;

	/**
	 * Creates new form ManageRequest
	 */
	public ManageOrgRequest(JPanel userProcessContainer, Enterprise enterprise, EcoSystem business,
			Organization organization) {
		initComponents();
		this.userProcessContainer = userProcessContainer;
		this.enterprise = enterprise;
		this.business = business;
		this.organization = organization;
		tblMechanic.getTableHeader().setDefaultRenderer(new HeaderColors());
		populateTable();

		// populateEmployeeCombo();
	}

	/*
	 * private void populateEmployeeCombo(){
	 * BoxAssignMaintanenceEmployee.removeAllItems(); if(BoxAssignMaintanenceOrg )
	 * 
	 * }
	 */
	private void populateTable() {
		tblMechanic.getTableHeader().setDefaultRenderer(new HeaderColors());
		DefaultTableModel model = (DefaultTableModel) tblMechanic.getModel();
		model.setRowCount(0);
		ArrayList<UserAccount> userAccountList = business.getUserAccountDirectory().getUserAccountList();
		for (UserAccount account : userAccountList) {
			for (ServiceRequest wr : account.getServiceDirectory().getServiceRequestList()) {
				if (wr.getEnterprisetype().getValue().equalsIgnoreCase("Maintanence")
						&& (wr.getStatus().equalsIgnoreCase("Processed by BodyShop")
								|| wr.getStatus().equalsIgnoreCase("Assigned to me"))) {
					Object[] row = new Object[model.getColumnCount()];
					row[0] = ((ServiceRequest) wr);
					row[1] = ((ServiceRequest) wr).getName();
					row[2] = ((ServiceRequest) wr).getModel();
					row[3] = ((ServiceRequest) wr).getMake();
					row[4] = ((ServiceRequest) wr).getModelyear();
					row[5] = ((ServiceRequest) wr).getRegno();
					row[6] = ((ServiceRequest) wr).getEnterprisetype().getValue();
					row[7] = ((ServiceRequest) wr).getStatus();
                                        row[8] = ((ServiceRequest) wr).getSender();

					model.addRow(row);
				}

			}
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMechanic = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        BoxAssignMaintanenceEmployee = new javax.swing.JComboBox<>();
        btnAssign = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Manage Service Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 300, 40));

        tblMechanic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Name", "Model", "Make", "Model Year", "Registration number", "Service Requested", "Status", "Sender"
            }
        ));
        jScrollPane1.setViewportView(tblMechanic);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 740, 90));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Employee");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, 20));

        BoxAssignMaintanenceEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(BoxAssignMaintanenceEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 110, -1));

        btnAssign.setBackground(new java.awt.Color(255, 255, 255));
        btnAssign.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAssign.setForeground(new java.awt.Color(0, 51, 153));
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 120, 20));

        btnProcess.setBackground(new java.awt.Color(255, 255, 255));
        btnProcess.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProcess.setForeground(new java.awt.Color(0, 51, 153));
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 120, 20));
    }// </editor-fold>//GEN-END:initComponents

	private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAssignActionPerformed
		// TODO add your handling code here:
		int count = tblMechanic.getSelectedRowCount();
		if (count != 1) {
			JOptionPane.showMessageDialog(null, "Select one row", "Warning", JOptionPane.WARNING_MESSAGE);
		} else {
			int selectedRow = tblMechanic.getSelectedRow();
			ServiceRequest sr = (ServiceRequest) tblMechanic.getValueAt(selectedRow, 0);
			if (sr.getStatus().equals("Processed by BodyShop")) {

				String msg = JOptionPane.showInputDialog("Additional Message");
				sr.setStatus("Assigned to me");
			}
		}
		populateTable();

	}// GEN-LAST:event_btnAssignActionPerformed

	private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnProcessActionPerformed
		// TODO add your handling code here:
		int count = tblMechanic.getSelectedRowCount();
		if (count != 1) {
			JOptionPane.showMessageDialog(null, "Select one row", "Warning", JOptionPane.WARNING_MESSAGE);
		} else {
			int selectedRow = tblMechanic.getSelectedRow();
			ServiceRequest sr = (ServiceRequest) tblMechanic.getValueAt(selectedRow, 0);
			if (sr.getStatus().equals("Processed by BodyShop")) {
				JOptionPane.showMessageDialog(null, "First assign process");
			} else if (sr.getStatus().equals("Assigned to me")
					&& enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Maintanence")) {
				sr.setStatus("Ready for billing");
			} else if (sr.getStatus().equals("Assigned to me")
					&& enterprise.getEnterpriseType().getValue().equalsIgnoreCase("All")) {
				sr.setStatus("Processed by Mechanic");
			}
		}
		populateTable();
	}// GEN-LAST:event_btnProcessActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxAssignMaintanenceEmployee;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMechanic;
    // End of variables declaration//GEN-END:variables
}
