/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.InteriorCleaningOrganization;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Workqueue.ServiceRequest;
import Utils.HeaderColors;
import java.util.ArrayList;

/**
 *
 * @author shaur
 */
public class ManageCleaningRequest extends javax.swing.JPanel {
	JPanel userProcessContainer;
	UserAccount account;
	Organization organization;
	Enterprise enterprise;
	Network network;
	EcoSystem business;

	/**
	 * Creates new form ManageRequest
	 */
	public ManageCleaningRequest(JPanel userProcessContainer, Enterprise enterprise, EcoSystem business,
			Organization organization) {
		initComponents();
		this.userProcessContainer = userProcessContainer;
		this.enterprise = enterprise;
		this.business = business;
		this.organization = organization;
		tblCleanerInterior.getTableHeader().setDefaultRenderer(new HeaderColors());
		populateTable();

	}

	private void populateTable() {
		tblCleanerInterior.getTableHeader().setDefaultRenderer(new HeaderColors());
		DefaultTableModel model = (DefaultTableModel) tblCleanerInterior.getModel();
		model.setRowCount(0);
		ArrayList<UserAccount> userAccountList = business.getUserAccountDirectory().getUserAccountList();
		for (UserAccount account : userAccountList) {
			for (ServiceRequest wr : account.getServiceDirectory().getServiceRequestList()) {
				if (wr.getStatus().equalsIgnoreCase("New") || wr.getStatus().equalsIgnoreCase("Assigned to me")
                                    || wr.getStatus().equalsIgnoreCase("Processed by Mechanic"))
                                    if (wr.getEnterprisetype().getValue().equalsIgnoreCase("Cleaning")
                                            || wr.getEnterprisetype().getValue().equalsIgnoreCase("All")) {
					Object[] row = new Object[model.getColumnCount()];
					row[0] = ((ServiceRequest) wr);
					row[1] = ((ServiceRequest) wr).getName();
					row[2] = ((ServiceRequest) wr).getModel();
					row[3] = ((ServiceRequest) wr).getMake();
					row[4] = ((ServiceRequest) wr).getModelyear();
					row[5] = ((ServiceRequest) wr).getRegno();
					row[6] = ((ServiceRequest) wr).getEnterprisetype().getValue();
					row[7] = ((ServiceRequest) wr).getStatus();
					row[8] = ((ServiceRequest) wr).getSender();

					model.addRow(row);
				}

			}
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblCleanerInterior = new javax.swing.JTable();
		jLabel4 = new javax.swing.JLabel();
		BoxAssignMaintanenceEmployee = new javax.swing.JComboBox<>();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setBackground(new java.awt.Color(255, 255, 255));
		setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 51, 153));
		jLabel1.setText("Manage Service Request");
		add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 300, 40));

		tblCleanerInterior.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null } },
				new String[] { "Request ID", "Name", "Model", "Make", "Model Year", "Registration number", "Service Requested",
						"Status", "Sender" }));
		jScrollPane1.setViewportView(tblCleanerInterior);

		add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 740, 90));

		jLabel4.setBackground(new java.awt.Color(255, 255, 255));
		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(204, 0, 51));
		jLabel4.setText("Employee");
		add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, 20));

		BoxAssignMaintanenceEmployee.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		add(BoxAssignMaintanenceEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 110, -1));

		jButton1.setBackground(new java.awt.Color(255, 255, 255));
		jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jButton1.setForeground(new java.awt.Color(0, 51, 153));
		jButton1.setText("Complete");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 160, 20));

		jButton2.setBackground(new java.awt.Color(255, 255, 255));
		jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jButton2.setForeground(new java.awt.Color(0, 51, 153));
		jButton2.setText("Assign");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 160, 20));
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		int count = tblCleanerInterior.getSelectedRowCount();
		if (count != 1) {
			JOptionPane.showMessageDialog(null, "Select one row", "Warning", JOptionPane.WARNING_MESSAGE);
		} else {
			int selectedRow = tblCleanerInterior.getSelectedRow();
			ServiceRequest sr = (ServiceRequest) tblCleanerInterior.getValueAt(selectedRow, 0);
			if (sr.getStatus().equalsIgnoreCase("New") || sr.getStatus().equalsIgnoreCase("Processed by Mechanic")) {

				String msg = JOptionPane.showInputDialog("Additional Message");
				sr.setStatus("Assigned to me");
			}
                         populateTable();
		}
               

	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		int count = tblCleanerInterior.getSelectedRowCount();
		if (count != 1) {
			JOptionPane.showMessageDialog(null, "Select one row", "Warning", JOptionPane.WARNING_MESSAGE);
		} else {
			int selectedRow = tblCleanerInterior.getSelectedRow();
			ServiceRequest sr = (ServiceRequest) tblCleanerInterior.getValueAt(selectedRow, 0);
			if (sr.getStatus().equalsIgnoreCase("New") || sr.getStatus().equalsIgnoreCase("Processed by Mechanic")) {
				JOptionPane.showMessageDialog(null, "First assign process");
			} else if (sr.getStatus().equals("Assigned")) {
				sr.setStatus("Processed by Interior Cleaner");
			}
                        populateTable();
		}
                
	}// GEN-LAST:event_jButton1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox<String> BoxAssignMaintanenceEmployee;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tblCleanerInterior;
	// End of variables declaration//GEN-END:variables
}
