/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Billing;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Workqueue.ServiceRequest;
import Business.Workqueue.ServiceRequestDirectory;
import Utils.HeaderColors;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shaur
 */
public class BillingRequest extends javax.swing.JPanel {
	JPanel userProcessContainer;
	UserAccount account;
	Organization organization;
	Enterprise enterprise;
	Network network;
	EcoSystem business;
	ServiceRequestDirectory servicerequestdirectory;
	Customer customer;

	/**
	 * Creates new form BillingRequest
	 */
	public BillingRequest(JPanel userProcessContainer, Network network, Enterprise enterprise, UserAccount account,
			EcoSystem business, Organization organization, ServiceRequestDirectory sd) {
		initComponents();
		this.userProcessContainer = userProcessContainer;
		this.enterprise = enterprise;
		this.business = business;
		this.organization = organization;
		this.account = account;
		this.servicerequestdirectory = sd;
		this.network = network;
		tblBilling.getTableHeader().setDefaultRenderer(new HeaderColors());
		populateTable();
	}

	private void populateTable() {
		tblBilling.getTableHeader().setDefaultRenderer(new HeaderColors());
		DefaultTableModel model = (DefaultTableModel) tblBilling.getModel();
		model.setRowCount(0);
		ArrayList<UserAccount> userAccountList = business.getUserAccountDirectory().getUserAccountList();
		for (UserAccount account : userAccountList) {
			for (ServiceRequest wr : account.getServiceDirectory().getServiceRequestList()) {
				if (wr.getStatus().equalsIgnoreCase("Ready for Billing")
						|| (wr.getStatus().equalsIgnoreCase("Email sent"))
						|| wr.getStatus().equalsIgnoreCase("Service Request completed")) {
					Object[] row = new Object[model.getColumnCount()];
					row[0] = ((ServiceRequest) wr);
					row[1] = ((ServiceRequest) wr).getName();
					row[2] = ((ServiceRequest) wr).getModel();
					row[3] = ((ServiceRequest) wr).getMake();
					row[4] = ((ServiceRequest) wr).getModelyear();
					row[5] = ((ServiceRequest) wr).getRegno();
					row[6] = ((ServiceRequest) wr).getEnterprisetype().getValue();
					row[7] = ((ServiceRequest) wr).getStatus();
					row[8] = ((ServiceRequest) wr).getSender();

					model.addRow(row);
				}

			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblBilling = new javax.swing.JTable();
		btnSendEmail = new javax.swing.JButton();
		btnCompleteRequest = new javax.swing.JButton();

		setBackground(new java.awt.Color(255, 255, 255));
		setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 51, 153));
		jLabel1.setText("Manage Service Request");
		add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 300, 40));

		tblBilling.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null } },
				new String[] { "Request ID", "Name", "Model", "Make", "Model Year", "Registration number",
						"Service Requested", "Status", "Sender" }));
		jScrollPane1.setViewportView(tblBilling);

		add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 740, 90));

		btnSendEmail.setBackground(new java.awt.Color(255, 255, 255));
		btnSendEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		btnSendEmail.setForeground(new java.awt.Color(0, 51, 153));
		btnSendEmail.setText("Send Email");
		btnSendEmail.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btnSendEmailMousePressed(evt);
			}
		});
		btnSendEmail.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSendEmailActionPerformed(evt);
			}
		});
		add(btnSendEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 140, 20));

		btnCompleteRequest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		btnCompleteRequest.setForeground(new java.awt.Color(0, 51, 153));
		btnCompleteRequest.setText("Complete Request");
		btnCompleteRequest.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btnCompleteRequestMousePressed(evt);
			}
		});
		add(btnCompleteRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 140, -1));
	}// </editor-fold>//GEN-END:initComponents

	private void btnSendEmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSendEmailActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnSendEmailActionPerformed

	private void btnSendEmailMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnSendEmailMousePressed
		// TODO add your handling code here:
		int count = tblBilling.getSelectedRowCount();
		if (count != 1) {
			JOptionPane.showMessageDialog(null, "Select one row", "Warning", JOptionPane.WARNING_MESSAGE);
		} else {
			int selectedRow = tblBilling.getSelectedRow();
			ServiceRequest sr = (ServiceRequest) tblBilling.getValueAt(selectedRow, 0);
			if (sr.getStatus().equalsIgnoreCase("Ready for billing")) {
				JOptionPane.showMessageDialog(null, "Email sent to customer.");

				sr.setStatus("Email sent");
				sr.setSender(account);
			}
		}
		populateTable();
	}// GEN-LAST:event_btnSendEmailMousePressed

	private void btnCompleteRequestMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCompleteRequestMousePressed
		// TODO add your handling code here:
		int count = tblBilling.getSelectedRowCount();
		if (count != 1) {
			JOptionPane.showMessageDialog(null, "Select one row", "Warning", JOptionPane.WARNING_MESSAGE);
		} else {
			int selectedRow = tblBilling.getSelectedRow();
			ServiceRequest sr = (ServiceRequest) tblBilling.getValueAt(selectedRow, 0);
			if (sr.getStatus().equals("Ready for billing")) {
				JOptionPane.showMessageDialog(null, "First send email to customer");
			} else if (sr.getStatus().equalsIgnoreCase("Email sent")) {
				sr.setStatus("Service Request completed");
				sr.setSender(account);
			}
		}
		populateTable();
	}// GEN-LAST:event_btnCompleteRequestMousePressed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCompleteRequest;
	private javax.swing.JButton btnSendEmail;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tblBilling;
	// End of variables declaration//GEN-END:variables
}
