/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SparePartsSalesAdmin;

import java.awt.CardLayout;
import java.awt.Color;

import javax.swing.JPanel;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;

/**
 *
 * @author shaur
 */
public class SparePartsSalesAdminWorkAreaJPanel extends javax.swing.JPanel {
	private Enterprise enterprise;
	private JPanel userProcessContainer;
	Network network;
	Organization organization;
	EcoSystem system;
	UserAccount account;

	/**
	 * Creates new form SparePartsAdminJPanel
	 */
	public SparePartsSalesAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,
			Organization organization, Enterprise enterprise, Network network, EcoSystem business) {
		initComponents();
		this.userProcessContainer = userProcessContainer;
		this.enterprise = enterprise;
		this.network = network;
		this.organization = organization;
		this.system = business;
		this.account = account;
	}

	public void manageRequest() {
		ManageRequest.setBackground(new Color(236, 113, 107));
		//ManageEmployeePanel.setBackground(new Color(215, 81, 81));

		ManageSparePartRequest ManageRequestPanel = new ManageSparePartRequest(SparePartsRightPanel, enterprise, system,
				organization);
		SparePartsRightPanel.add("MangeRequest", ManageRequestPanel);
		CardLayout layout = (CardLayout) SparePartsRightPanel.getLayout();
		layout.next(SparePartsRightPanel);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SparePartsAdminWorkArea = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ManageRequest = new javax.swing.JPanel();
        LabelSparePartsManageRequests = new javax.swing.JLabel();
        SparePartsRightPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        SparePartsAdminWorkArea.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(191, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageRequest.setBackground(new java.awt.Color(191, 0, 0));
        ManageRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageRequestMousePressed(evt);
            }
        });

        LabelSparePartsManageRequests.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LabelSparePartsManageRequests.setForeground(new java.awt.Color(0, 51, 153));
        LabelSparePartsManageRequests.setText("Manage Requests");
        LabelSparePartsManageRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelSparePartsManageRequestsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ManageRequestLayout = new javax.swing.GroupLayout(ManageRequest);
        ManageRequest.setLayout(ManageRequestLayout);
        ManageRequestLayout.setHorizontalGroup(
            ManageRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageRequestLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(LabelSparePartsManageRequests, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        ManageRequestLayout.setVerticalGroup(
            ManageRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageRequestLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LabelSparePartsManageRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(ManageRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 50));

        SparePartsRightPanel.setBackground(new java.awt.Color(255, 255, 255));
        SparePartsRightPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout SparePartsAdminWorkAreaLayout = new javax.swing.GroupLayout(SparePartsAdminWorkArea);
        SparePartsAdminWorkArea.setLayout(SparePartsAdminWorkAreaLayout);
        SparePartsAdminWorkAreaLayout.setHorizontalGroup(
            SparePartsAdminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SparePartsAdminWorkAreaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SparePartsRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SparePartsAdminWorkAreaLayout.setVerticalGroup(
            SparePartsAdminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addComponent(SparePartsRightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(SparePartsAdminWorkArea, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	private void ManageRequestMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ManageRequestMousePressed
		// TODO add your handling code here:
		manageRequest();
	}// GEN-LAST:event_ManageRequestMousePressed

	private void LabelSparePartsManageRequestsMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_LabelSparePartsManageRequestsMousePressed
		// TODO add your handling code here:
		manageRequest();
	}// GEN-LAST:event_LabelSparePartsManageRequestsMousePressed

	private void ManageEmployeePanelMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ManageEmployeePanelMousePressed
		// TODO add your handling code here:

	}// GEN-LAST:event_ManageEmployeePanelMousePressed

	private void LabelSparePartsManageEmployeeMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_LabelSparePartsManageEmployeeMousePressed
		// TODO add your handling code here:

	}// GEN-LAST:event_LabelSparePartsManageEmployeeMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelSparePartsManageRequests;
    private javax.swing.JPanel ManageRequest;
    private javax.swing.JPanel SparePartsAdminWorkArea;
    private javax.swing.JPanel SparePartsRightPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
