/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Customer;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import Business.EcoSystem;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.Workqueue.ServiceRequest;
import Business.Workqueue.ServiceRequestDirectory;

/**
 *
 * @author shaur
 */
public class CustomerJPanel extends javax.swing.JPanel {
	private JPanel userProcessContainer;
	Network network;
	EcoSystem system;
	UserAccount account;
	ServiceRequestDirectory serviceDirectory;
        

	/**
	 * Creates new form CustomerWorkArea
	 */
	public CustomerJPanel(JPanel userProcessContainer, UserAccount account, Network network, EcoSystem system,
			ServiceRequestDirectory sd) {
		initComponents();
		this.userProcessContainer = userProcessContainer;

		this.network = network;

		this.system = system;
		this.account = account;
		this.serviceDirectory = sd;
		populateComboBox();
		populateCityComboBox();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void populateComboBox() {
		BoxServiceRequired.removeAllItems();
		BoxServiceRequired.addItem("Maintanence");
		BoxServiceRequired.addItem("Cleaning");
		BoxServiceRequired.addItem("Spare Parts");
		BoxServiceRequired.addItem("All");
	}

	private void populateCityComboBox() {
		BoxCustomerCity.removeAllItems();
		for (Network network : system.getNetworkList()) {
			BoxCustomerCity.addItem(network);
		}

	}

	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		TFCustomerName = new javax.swing.JTextField();
		TFCustomerRegNo = new javax.swing.JTextField();
		TFDescription = new javax.swing.JTextField();
		TFMake = new javax.swing.JTextField();
		TFModel = new javax.swing.JTextField();
		BoxCustomerCity = new javax.swing.JComboBox();
		jButton1 = new javax.swing.JButton();
		jLabel13 = new javax.swing.JLabel();
		TFModelYear = new javax.swing.JTextField();
		jLabel14 = new javax.swing.JLabel();
		BoxServiceRequired = new javax.swing.JComboBox<>();

		setBackground(new java.awt.Color(255, 255, 255));
		setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 51, 153));
		jLabel1.setText("We value your need");
		add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 240, 40));

		jLabel3.setBackground(new java.awt.Color(255, 255, 255));
		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(204, 0, 51));
		jLabel3.setText("Name");
		add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

		jLabel4.setBackground(new java.awt.Color(255, 255, 255));
		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(204, 0, 51));
		jLabel4.setText("Vehicle Registration No.");
		add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

		jLabel7.setBackground(new java.awt.Color(255, 255, 255));
		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(204, 0, 51));
		jLabel7.setText("Manufacturer");
		add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

		jLabel10.setBackground(new java.awt.Color(255, 255, 255));
		jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(204, 0, 51));
		jLabel10.setText("Model");
		add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

		jLabel11.setBackground(new java.awt.Color(255, 255, 255));
		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(204, 0, 51));
		jLabel11.setText("Additional Remarks");
		add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

		jLabel12.setBackground(new java.awt.Color(255, 255, 255));
		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(204, 0, 51));
		jLabel12.setText("City");
		add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));
		add(TFCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 160, -1));

		TFCustomerRegNo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TFCustomerRegNoActionPerformed(evt);
			}
		});
		add(TFCustomerRegNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 160, -1));
		add(TFDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 160, 40));
		add(TFMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 160, -1));
		add(TFModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 160, -1));

		BoxCustomerCity.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		BoxCustomerCity.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BoxCustomerCityActionPerformed(evt);
			}
		});
		add(BoxCustomerCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 160, -1));

		jButton1.setBackground(new java.awt.Color(255, 255, 255));
		jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jButton1.setForeground(new java.awt.Color(0, 51, 153));
		jButton1.setText("Submit");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 160, -1));

		jLabel13.setBackground(new java.awt.Color(255, 255, 255));
		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(204, 0, 51));
		jLabel13.setText("Service Required");
		add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));
		add(TFModelYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 160, -1));

		jLabel14.setBackground(new java.awt.Color(255, 255, 255));
		jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel14.setForeground(new java.awt.Color(204, 0, 51));
		jLabel14.setText("Model Year");
		add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

		BoxServiceRequired.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		BoxServiceRequired.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BoxServiceRequiredActionPerformed(evt);
			}
		});
		add(BoxServiceRequired, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 160, -1));
	}// </editor-fold>//GEN-END:initComponents

	private void TFCustomerRegNoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TFCustomerRegNoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TFCustomerRegNoActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		// object of the request
		// text fields entry
		// use setter t for the object (request.addname)
		// pass this in the object again
		ServiceRequest sr = new ServiceRequest();
		sr.setName(TFCustomerName.getText());
		sr.setRegno(TFCustomerRegNo.getText());
		sr.setModel(TFModel.getText());
		sr.setMake(TFMake.getText());
		sr.setModelyear(TFModelYear.getText());
		sr.setDescription(TFDescription.getText());
		String ent1 = (String) BoxServiceRequired.getSelectedItem();
		if (ent1.equalsIgnoreCase("Maintanence"))// EnterpriseType.Maintanence.getValue()
			sr.setEnterprisetype(EnterpriseType.Maintanence);
		if (ent1.equalsIgnoreCase("Cleaning"))
			sr.setEnterprisetype(EnterpriseType.Cleaning);
		if (ent1.equalsIgnoreCase("Spare Parts"))
			sr.setEnterprisetype(EnterpriseType.SpareParts);
		if (ent1.equalsIgnoreCase("All"))
			sr.setEnterprisetype(EnterpriseType.All);
		sr.setSender(account);
		sr.setCustomercity(network);

		sr.setStatus("New");
                sr.setSender(account);

//        Customer cust = system.getCustomerDirectory().findUserByUserName(TFCustomerName.getText());
		account.getServiceDirectory().createRequest(sr);
		JOptionPane.showMessageDialog(null, "Your Service is registered.");

		// if(Ent1 == Enterprisetype.("Maintanence"))

//        for(WorkRequest wr : account.getWorkQueue().getWorkRequestList()){
//            if(ent1.getType().getValue().equalsIgnoreCase("Maintenance")){
//                
//            }
//        }

	}// GEN-LAST:event_jButton1ActionPerformed

	private void BoxCustomerCityActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BoxCustomerCityActionPerformed
		// TODO add your handling code here:
		populateComboBox();
	}// GEN-LAST:event_BoxCustomerCityActionPerformed

	private void BoxServiceRequiredActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BoxServiceRequiredActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_BoxServiceRequiredActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox BoxCustomerCity;
	private javax.swing.JComboBox<String> BoxServiceRequired;
	private javax.swing.JTextField TFCustomerName;
	private javax.swing.JTextField TFCustomerRegNo;
	private javax.swing.JTextField TFDescription;
	private javax.swing.JTextField TFMake;
	private javax.swing.JTextField TFModel;
	private javax.swing.JTextField TFModelYear;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel7;
	// End of variables declaration//GEN-END:variables
}
