/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SysAdmin;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Utils.HeaderColors;

/**
 *
 * @author shaur
 */
public class SysAdminManageEnterprise extends javax.swing.JPanel {
	private JPanel userProcessContainer;
	private EcoSystem system;

	/**
	 * Creates new form SysAdminManageEnterprise
	 */
	public SysAdminManageEnterprise(JPanel userProcessContainer, EcoSystem system) {
		initComponents();
		this.userProcessContainer = userProcessContainer;
		this.system = system;
		TableManageEnterprise.getTableHeader().setDefaultRenderer(new HeaderColors());
		populateTable();
		populateComboBox();
	}

	private void populateTable() {
		TableManageEnterprise.getTableHeader().setDefaultRenderer(new HeaderColors());
		DefaultTableModel model = (DefaultTableModel) TableManageEnterprise.getModel();

		model.setRowCount(0);
		for (Network network : system.getNetworkList()) {
			for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
				Object[] row = new Object[3];
				row[0] = enterprise.getName();
				row[1] = network.getName();
				row[2] = enterprise.getEnterpriseType().getValue();

				model.addRow(row);
			}
		}
	}

	private void populateComboBox() {
		BoxNetworkList.removeAllItems();
		BoxEnterpriseList.removeAllItems();

		for (Network network : system.getNetworkList()) {
			BoxNetworkList.addItem(network);
		}

		for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
			BoxEnterpriseList.addItem(type);
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		TableManageEnterprise = new javax.swing.JTable();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		BoxNetworkList = new javax.swing.JComboBox<>();
		TFEnterpriseName = new javax.swing.JTextField();
		BtnSubmitEnterprise = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		BoxEnterpriseList = new javax.swing.JComboBox();

		setBackground(new java.awt.Color(255, 255, 255));
		setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		TableManageEnterprise.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null, null },
				{ null, null, null }, { null, null, null }, { null, null, null } },
				new String[] { "Enterprise", "Network", "Type" }));
		jScrollPane1.setViewportView(TableManageEnterprise);

		add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 670, 90));

		jLabel2.setBackground(new java.awt.Color(255, 255, 255));
		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(0, 51, 153));
		jLabel2.setText("Name");
		add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

		jLabel3.setBackground(new java.awt.Color(255, 255, 255));
		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(0, 51, 153));
		jLabel3.setText("Network");
		add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

		jLabel4.setBackground(new java.awt.Color(255, 255, 255));
		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(0, 51, 153));
		jLabel4.setText("Enterprise");
		add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

		BoxNetworkList.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		add(BoxNetworkList, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 180, -1));

		TFEnterpriseName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TFEnterpriseNameActionPerformed(evt);
			}
		});
		add(TFEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 180, -1));

		BtnSubmitEnterprise.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		BtnSubmitEnterprise.setForeground(new java.awt.Color(0, 51, 153));
		BtnSubmitEnterprise.setText("Submit");
		BtnSubmitEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				BtnSubmitEnterpriseMousePressed(evt);
			}
		});
		BtnSubmitEnterprise.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnSubmitEnterpriseActionPerformed(evt);
			}
		});
		add(BtnSubmitEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 130, -1));

		jLabel1.setBackground(new java.awt.Color(255, 255, 255));
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SysadminManageenterprise.jpg"))); // NOI18N
		add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 210, 230));

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(0, 51, 153));
		jLabel5.setText("Manage Enterprise");
		add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 230, 40));

		BoxEnterpriseList.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
		BoxEnterpriseList.setForeground(new java.awt.Color(25, 56, 82));
		BoxEnterpriseList.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		add(BoxEnterpriseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 180, -1));
	}// </editor-fold>//GEN-END:initComponents

	private void TFEnterpriseNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TFEnterpriseNameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TFEnterpriseNameActionPerformed

	private void BtnSubmitEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnSubmitEnterpriseActionPerformed
		Network network = (Network) BoxNetworkList.getSelectedItem();
		Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) BoxEnterpriseList.getSelectedItem();

		if (network == null || type == null) {
			JOptionPane.showMessageDialog(null, "Invalid Input!");
			return;
		}

		String name = TFEnterpriseName.getText();
		if (!name.isEmpty()) {
			network.getEnterpriseDirectory().createAndAddEnterprise(name, type);
			JOptionPane.showMessageDialog(null, "Enterprise created sucessfully!");
			TFEnterpriseName.setText("");
			populateTable();
		} else {
			JOptionPane.showMessageDialog(null, "Enter enterprise name");
		} // TODO add your handling code here:
	}// GEN-LAST:event_BtnSubmitEnterpriseActionPerformed

	private void BtnSubmitEnterpriseMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_BtnSubmitEnterpriseMousePressed
		// TODO add your handling code here:
		Network network = (Network) BoxNetworkList.getSelectedItem();
		Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) BoxEnterpriseList.getSelectedItem();

		if (network == null || type == null) {
			JOptionPane.showMessageDialog(null, "Invalid Input!");
			return;
		}

		String name = TFEnterpriseName.getText();
		if (!name.isEmpty()) {
			network.getEnterpriseDirectory().createAndAddEnterprise(name, type);
			JOptionPane.showMessageDialog(null, "Enterprise created sucessfully!");
			TFEnterpriseName.setText("");
			populateTable();
		} else {
			JOptionPane.showMessageDialog(null, "Enter enterprise name");
		}
	}// GEN-LAST:event_BtnSubmitEnterpriseMousePressed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox BoxEnterpriseList;
	private javax.swing.JComboBox<Object> BoxNetworkList;
	private javax.swing.JButton BtnSubmitEnterprise;
	private javax.swing.JTextField TFEnterpriseName;
	private javax.swing.JTable TableManageEnterprise;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}
