/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SysAdmin;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import Business.EcoSystem;
import Business.Network.Network;
import Utils.HeaderColors;

/**
 *
 * @author shaur
 */
public class SysAdminManageNetwork extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form SysAdminManageNetwork
     */
    public SysAdminManageNetwork(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
networkJTable.getTableHeader().setDefaultRenderer(new HeaderColors());
        populateNetworkTable();
    }
    
    private void populateNetworkTable() {
        networkJTable.getTableHeader().setDefaultRenderer(new HeaderColors());
        DefaultTableModel model = (DefaultTableModel) networkJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network.getName();
            model.addRow(row);
        }
    }
    
    private void submitButton() {
        String name = TFStateName.getText().trim();
        if(!name.isEmpty()){
            if(system.isUnique(name)){
                Network network = system.createAndAddNetwork();
                network.setName(name);
                JOptionPane.showMessageDialog(null, "Network Successfully Created");
                TFStateName.setText("");
            } else{
                JOptionPane.showMessageDialog(null, "Network Already Exits");
            }
        } else{
            JOptionPane.showMessageDialog(null, "Enter city name");
        }
        
        
        populateNetworkTable();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        networkJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        TFStateName = new javax.swing.JTextField();
        BtnSubmitEnterprise = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Manage Network");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 210, 40));

        networkJTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        networkJTable.setForeground(new java.awt.Color(25, 56, 82));
        networkJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        networkJTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        jScrollPane1.setViewportView(networkJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 567, 91));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("State");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));
        add(TFStateName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 180, -1));

        BtnSubmitEnterprise.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnSubmitEnterprise.setForeground(new java.awt.Color(0, 51, 153));
        BtnSubmitEnterprise.setText("Submit");
        BtnSubmitEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitEnterpriseActionPerformed(evt);
            }
        });
        add(BtnSubmitEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ManageNetwork.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSubmitEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitEnterpriseActionPerformed
        // TODO add your handling code here:
        submitButton();
    }//GEN-LAST:event_BtnSubmitEnterpriseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSubmitEnterprise;
    private javax.swing.JTextField TFStateName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable networkJTable;
    // End of variables declaration//GEN-END:variables
}
