/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SysAdmin;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.AccountsAdmin;
import Business.Role.CleaningAdmin;
import Business.Role.MaintenanceAdmin;
import Business.Role.SparePartsAdmin;
import Business.UserAccount.UserAccount;
import Utils.HeaderColors;

/**
 *
 * @author shaur
 */
public class SysAdminManageEnterpriseAdmin extends javax.swing.JPanel {
	private JPanel userProcessContainer;
	private EcoSystem system;

	/**
	 * Creates new form SysAdminManageEnterpriseAdmin
	 */
	public SysAdminManageEnterpriseAdmin(JPanel userProcessContainer, EcoSystem system) {
		initComponents();
		this.userProcessContainer = userProcessContainer;
		this.system = system;
		TableManageEnterpriseAdmin.getTableHeader().setDefaultRenderer(new HeaderColors());
		populateTable();
		populateNetworkComboBox();
	}

	private void populateTable() {
		TableManageEnterpriseAdmin.getTableHeader().setDefaultRenderer(new HeaderColors());
		DefaultTableModel model = (DefaultTableModel) TableManageEnterpriseAdmin.getModel();

		model.setRowCount(0);
		for (Network network : system.getNetworkList()) {
			for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
				for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
					Object[] row = new Object[3];
					row[0] = enterprise.getName();
					row[1] = network.getName();
					row[2] = userAccount.getUsername();

					model.addRow(row);
				}
			}
		}
	}

	private void populateNetworkComboBox() {
		BoxManageAdminNetworkList.removeAllItems();
		BoxManageAdminEnterpriseList.removeAllItems();

		for (Network network : system.getNetworkList()) {
			BoxManageAdminNetworkList.addItem(network);
		}
	}

	private void populateEnterpriseComboBox(Network network) {
		BoxManageAdminEnterpriseList.removeAllItems();

		for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
			BoxManageAdminEnterpriseList.addItem(enterprise);
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		TableManageEnterpriseAdmin = new javax.swing.JTable();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		BoxManageAdminEnterpriseList = new javax.swing.JComboBox();
		BoxManageAdminNetworkList = new javax.swing.JComboBox();
		TFManageAdminPassword = new javax.swing.JTextField();
		BtnSubmitEnterpriseAdmin = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		TFManageAdminName = new javax.swing.JTextField();
		TFManageAdminUsername = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();

		setBackground(new java.awt.Color(255, 255, 255));
		setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 51, 153));
		jLabel1.setText("Manage Enterprise Admin");
		add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 310, 40));

		TableManageEnterpriseAdmin.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {
				{ null, null, null }, { null, null, null }, { null, null, null }, { null, null, null } },
				new String[] { "Enterprise", "Network", "Username" }));
		jScrollPane1.setViewportView(TableManageEnterpriseAdmin);

		add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 670, 90));

		jLabel2.setBackground(new java.awt.Color(255, 255, 255));
		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(0, 51, 153));
		jLabel2.setText("Name");
		add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

		jLabel3.setBackground(new java.awt.Color(255, 255, 255));
		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(0, 51, 153));
		jLabel3.setText("Network");
		add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

		jLabel4.setBackground(new java.awt.Color(255, 255, 255));
		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(0, 51, 153));
		jLabel4.setText("Password");
		add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

		BoxManageAdminEnterpriseList.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		add(BoxManageAdminEnterpriseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 180, -1));

		BoxManageAdminNetworkList.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		BoxManageAdminNetworkList.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BoxManageAdminNetworkListActionPerformed(evt);
			}
		});
		add(BoxManageAdminNetworkList, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 180, -1));

		TFManageAdminPassword.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TFManageAdminPasswordActionPerformed(evt);
			}
		});
		add(TFManageAdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 180, -1));

		BtnSubmitEnterpriseAdmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		BtnSubmitEnterpriseAdmin.setForeground(new java.awt.Color(0, 51, 153));
		BtnSubmitEnterpriseAdmin.setText("Submit");
		BtnSubmitEnterpriseAdmin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnSubmitEnterpriseAdminActionPerformed(evt);
			}
		});
		add(BtnSubmitEnterpriseAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 130, -1));

		jLabel5.setBackground(new java.awt.Color(255, 255, 255));
		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(0, 51, 153));
		jLabel5.setText("Enterprise");
		add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

		jLabel6.setBackground(new java.awt.Color(255, 255, 255));
		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(0, 51, 153));
		jLabel6.setText("Username");
		add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

		TFManageAdminName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TFManageAdminNameActionPerformed(evt);
			}
		});
		add(TFManageAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 180, -1));

		TFManageAdminUsername.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TFManageAdminUsernameActionPerformed(evt);
			}
		});
		add(TFManageAdminUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 180, -1));

		jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ManageEnterpriseAdmin.jpg"))); // NOI18N
		add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));
	}// </editor-fold>//GEN-END:initComponents

	private void TFManageAdminPasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TFManageAdminPasswordActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TFManageAdminPasswordActionPerformed

	private void TFManageAdminNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TFManageAdminNameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TFManageAdminNameActionPerformed

	private void TFManageAdminUsernameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TFManageAdminUsernameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TFManageAdminUsernameActionPerformed

	private void BtnSubmitEnterpriseAdminActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnSubmitEnterpriseAdminActionPerformed
		// TODO add your handling code here:
		Enterprise enterprise = (Enterprise) BoxManageAdminEnterpriseList.getSelectedItem();

		String username = TFManageAdminUsername.getText();
		String password = String.valueOf(TFManageAdminPassword.getText());
		String name = TFManageAdminName.getText();
		if (username.isEmpty() || password.isEmpty() || name.isEmpty()) {
			JOptionPane.showMessageDialog(null, "Please enter all fields", "Warning", JOptionPane.WARNING_MESSAGE);
		} else {
			Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);

			if (system.checkIfUserIsUnique(username)) {
				UserAccount account = null;
				if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Maintanence) {
					account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee,
							new MaintenanceAdmin());
				} else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Cleaning) {
					account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee,
							new CleaningAdmin());
				} else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.SpareParts) {
					account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee,
							new SparePartsAdmin());
				} else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Accounts) {
					account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee,
							new AccountsAdmin());
				}

				TFManageAdminUsername.setText("");
				TFManageAdminPassword.setText("");
				TFManageAdminName.setText("");
				JOptionPane.showMessageDialog(null, "Account created sucessfully");
				populateTable();
			} else {
				JOptionPane.showMessageDialog(null, "Please enter unique username", "Warning",
						JOptionPane.WARNING_MESSAGE);
			}
		}

	}// GEN-LAST:event_BtnSubmitEnterpriseAdminActionPerformed

	private void BoxManageAdminNetworkListActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BoxManageAdminNetworkListActionPerformed
		// TODO add your handling code here:
		Network network = (Network) BoxManageAdminNetworkList.getSelectedItem();
		if (network != null) {
			populateEnterpriseComboBox(network);
		}
	}// GEN-LAST:event_BoxManageAdminNetworkListActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox BoxManageAdminEnterpriseList;
	private javax.swing.JComboBox BoxManageAdminNetworkList;
	private javax.swing.JButton BtnSubmitEnterpriseAdmin;
	private javax.swing.JTextField TFManageAdminName;
	private javax.swing.JTextField TFManageAdminPassword;
	private javax.swing.JTextField TFManageAdminUsername;
	private javax.swing.JTable TableManageEnterpriseAdmin;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables
}
