/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SysAdmin;

import java.awt.CardLayout;
import java.awt.Color;

import javax.swing.JPanel;

import Business.EcoSystem;

/**
 *
 * @author shaur
 */
public class SysAdminWorkArea extends javax.swing.JPanel {
    JPanel userProcessContainer;
    EcoSystem ecosystem;

    /**
     * Creates new form SysAdminWorkArea
     */
    public SysAdminWorkArea(JPanel userProcessContainer,EcoSystem ecosystem) {
    
        initComponents();
        System.out.println("here");
        this.userProcessContainer=userProcessContainer;        
        this.ecosystem=ecosystem;
        manageNetwork();
    }
    
    private void manageNetwork(){
        ManageNetworkPanel.setBackground(new Color(236,113,107));
        ManageEnterprisePanel.setBackground(new Color(215,81,81));
        ManageEnterpriseAdminPanel.setBackground(new Color(215,81,81));
        
        ui.SysAdmin.SysAdminManageNetwork manageNetworkPanel = new ui.SysAdmin.SysAdminManageNetwork(SysAdminRightPanel, ecosystem);
        SysAdminRightPanel.add("SysAdminManageNetwork",manageNetworkPanel);
        CardLayout layout = (CardLayout) SysAdminRightPanel.getLayout();
        layout.next(SysAdminRightPanel);
     }
    
    
    private void manageEnterprise(){
        ManageEnterprisePanel.setBackground(new Color(236,113,107));
        ManageNetworkPanel.setBackground(new Color(215,81,81));
        ManageEnterpriseAdminPanel.setBackground(new Color(215,81,81));
       
        ui.SysAdmin.SysAdminManageEnterprise manageEnterprisePanel = new ui.SysAdmin.SysAdminManageEnterprise(SysAdminRightPanel, ecosystem);
        SysAdminRightPanel.add("SysAdminManageEnterprise",manageEnterprisePanel);
        CardLayout layout = (CardLayout) SysAdminRightPanel.getLayout();
        layout.next(SysAdminRightPanel);
    }
        
    private void manageEnterpriseAdmin(){
        
        ManageEnterpriseAdminPanel.setBackground(new Color(236,113,107));
        ManageEnterprisePanel.setBackground(new Color(215,81,81));
        ManageNetworkPanel.setBackground(new Color(215,81,81));
        
        SysAdminManageEnterpriseAdmin manageEnterpriseAdmin = new SysAdminManageEnterpriseAdmin(SysAdminRightPanel, ecosystem);
        SysAdminRightPanel.add("SysAdminManageEnterpriseAdmin",manageEnterpriseAdmin);
        CardLayout layout = (CardLayout) SysAdminRightPanel.getLayout();
        layout.next(SysAdminRightPanel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSysAdminWorkArea = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ManageNetworkPanel = new javax.swing.JPanel();
        LabelManageNetwork = new javax.swing.JLabel();
        ManageEnterprisePanel = new javax.swing.JPanel();
        LabelManageEnterprise = new javax.swing.JLabel();
        ManageEnterpriseAdminPanel = new javax.swing.JPanel();
        LabelManageEnterpriseAdmin = new javax.swing.JLabel();
        SysAdminRightPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(720, 720));
        setLayout(new java.awt.BorderLayout());

        PanelSysAdminWorkArea.setBackground(new java.awt.Color(255, 255, 255));
        PanelSysAdminWorkArea.setForeground(new java.awt.Color(255, 255, 255));
        PanelSysAdminWorkArea.setPreferredSize(new java.awt.Dimension(1360, 720));

        jPanel1.setBackground(new java.awt.Color(191, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageNetworkPanel.setBackground(new java.awt.Color(191, 0, 0));
        ManageNetworkPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageNetworkPanelMousePressed(evt);
            }
        });

        LabelManageNetwork.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LabelManageNetwork.setForeground(new java.awt.Color(0, 51, 153));
        LabelManageNetwork.setText("Manage Network");
        LabelManageNetwork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelManageNetworkMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ManageNetworkPanelLayout = new javax.swing.GroupLayout(ManageNetworkPanel);
        ManageNetworkPanel.setLayout(ManageNetworkPanelLayout);
        ManageNetworkPanelLayout.setHorizontalGroup(
            ManageNetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageNetworkPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(LabelManageNetwork, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        ManageNetworkPanelLayout.setVerticalGroup(
            ManageNetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageNetworkPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LabelManageNetwork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(ManageNetworkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 50));

        ManageEnterprisePanel.setBackground(new java.awt.Color(191, 0, 0));
        ManageEnterprisePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageEnterprisePanelMousePressed(evt);
            }
        });

        LabelManageEnterprise.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LabelManageEnterprise.setForeground(new java.awt.Color(0, 51, 153));
        LabelManageEnterprise.setText("Manage Enterprise");
        LabelManageEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelManageEnterpriseMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ManageEnterprisePanelLayout = new javax.swing.GroupLayout(ManageEnterprisePanel);
        ManageEnterprisePanel.setLayout(ManageEnterprisePanelLayout);
        ManageEnterprisePanelLayout.setHorizontalGroup(
            ManageEnterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageEnterprisePanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(LabelManageEnterprise)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        ManageEnterprisePanelLayout.setVerticalGroup(
            ManageEnterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageEnterprisePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelManageEnterprise)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(ManageEnterprisePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 40));

        ManageEnterpriseAdminPanel.setBackground(new java.awt.Color(191, 0, 0));
        ManageEnterpriseAdminPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageEnterpriseAdminPanelMousePressed(evt);
            }
        });

        LabelManageEnterpriseAdmin.setBackground(new java.awt.Color(204, 0, 51));
        LabelManageEnterpriseAdmin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LabelManageEnterpriseAdmin.setForeground(new java.awt.Color(0, 51, 153));
        LabelManageEnterpriseAdmin.setText("Manage Enterprise Admin");
        LabelManageEnterpriseAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelManageEnterpriseAdminMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ManageEnterpriseAdminPanelLayout = new javax.swing.GroupLayout(ManageEnterpriseAdminPanel);
        ManageEnterpriseAdminPanel.setLayout(ManageEnterpriseAdminPanelLayout);
        ManageEnterpriseAdminPanelLayout.setHorizontalGroup(
            ManageEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageEnterpriseAdminPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(LabelManageEnterpriseAdmin)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        ManageEnterpriseAdminPanelLayout.setVerticalGroup(
            ManageEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageEnterpriseAdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelManageEnterpriseAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(ManageEnterpriseAdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 300, 40));

        SysAdminRightPanel.setBackground(new java.awt.Color(255, 255, 255));
        SysAdminRightPanel.setPreferredSize(new java.awt.Dimension(1060, 720));
        SysAdminRightPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout PanelSysAdminWorkAreaLayout = new javax.swing.GroupLayout(PanelSysAdminWorkArea);
        PanelSysAdminWorkArea.setLayout(PanelSysAdminWorkAreaLayout);
        PanelSysAdminWorkAreaLayout.setHorizontalGroup(
            PanelSysAdminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSysAdminWorkAreaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SysAdminRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelSysAdminWorkAreaLayout.setVerticalGroup(
            PanelSysAdminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSysAdminWorkAreaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(SysAdminRightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(PanelSysAdminWorkArea, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void LabelManageNetworkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelManageNetworkMousePressed
        // TODO add your handling code here:
        manageNetwork();
    }//GEN-LAST:event_LabelManageNetworkMousePressed

    private void ManageNetworkPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageNetworkPanelMousePressed
        // TODO add your handling code here:
        manageNetwork();
    }//GEN-LAST:event_ManageNetworkPanelMousePressed

    private void ManageEnterprisePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageEnterprisePanelMousePressed
        // TODO add your handling code here:
        manageEnterprise();
    }//GEN-LAST:event_ManageEnterprisePanelMousePressed

    private void LabelManageEnterpriseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelManageEnterpriseMousePressed
        // TODO add your handling code here:
        manageEnterprise();
    }//GEN-LAST:event_LabelManageEnterpriseMousePressed

    private void ManageEnterpriseAdminPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageEnterpriseAdminPanelMousePressed
        // TODO add your handling code here:
        manageEnterpriseAdmin();
    }//GEN-LAST:event_ManageEnterpriseAdminPanelMousePressed

    private void LabelManageEnterpriseAdminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelManageEnterpriseAdminMousePressed
        // TODO add your handling code here:
        manageEnterpriseAdmin();
    }//GEN-LAST:event_LabelManageEnterpriseAdminMousePressed


    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelManageEnterprise;
    private javax.swing.JLabel LabelManageEnterpriseAdmin;
    private javax.swing.JLabel LabelManageNetwork;
    private javax.swing.JPanel ManageEnterpriseAdminPanel;
    private javax.swing.JPanel ManageEnterprisePanel;
    private javax.swing.JPanel ManageNetworkPanel;
    private javax.swing.JPanel PanelSysAdminWorkArea;
    private javax.swing.JPanel SysAdminRightPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
